apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ required "A valid number of replicas is required" .Values.Replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/role
                operator: In
                values:
                - node
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: failure-domain.beta.kubernetes.io/zone
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ .Release.Name }}
      containers:
      - name: fund-manager
        image: {{ required "A valid dockerRegistry is required" .Values.DockerRegistry }}/htmlhub
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        env:
        - name: GITHUB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: GithubPassword
